import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import loots from '../data/loots'
import Layout from '../components/layout';
import utilStyles from '../styles/utils.module.css';

const ParrotImage = () => (
  <Image
    src="/images/ParrotPirate.svg"
    height={350}
    width={700}
    alt="pirate parrot"
  />
);

export async function getStaticProps() {
  return {
    props: {
      allLootsData: loots
    },
  };
}

export default function Home({ allLootsData }) {
  return (
    <Layout home>
      <Head>
        <title>Looty</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <link rel="icon" href="/treasure-chest-favicon.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Looty!
        </h1>

        <ParrotImage />

        <p>Jump right in by searching for treasure on <Link href="/loots/emerald-isle">Emerald Isle</Link></p>
        <section className={`${utilStyles.headingMd} ${utilStyles.padding1px}`}>
        <h2 className={utilStyles.headingLg}>Blog</h2>
        <ul className={utilStyles.list}>
          {allLootsData.map(({ id, name, description }) => (
            <li className={utilStyles.listItem} key={id}>
              {name}
              <br />
              {id}
              <br />
              {description}
            </li>
          ))}
        </ul>
      </section>
      </main>
    </Layout>
  )
}
